# Generated by Django 6.0.6 on 2026-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_nick",
        ),
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм сhat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграм сhat-id",
            ),
        ),
    ]
