# Generated by Django 6.0.6 on 2026-07-06 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Выберите действие",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plesant_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="UsefulHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Выберите место выполнения",
                        max_length=150,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Введите время начала действия",
                        verbose_name="Время начала выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Выберите действие",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения в днях",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("10", "10 секунд"),
                            ("20", "20 секунд"),
                            ("30", "30 секунд"),
                            ("40", "40 секунд"),
                            ("50", "50 секунд"),
                            ("60", "60 секунд"),
                            ("70", "70 секунд"),
                            ("80", "80 секунд"),
                            ("90", "90 секунд"),
                            ("100", "100 секунд"),
                            ("110", "110 секунд"),
                            ("120", "120 секунд"),
                        ],
                        help_text="Укажите продолжительность",
                        max_length=10,
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликовать привычку?",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.pleasanthabit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="useful_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
    ]
